title: PSK Gamma Tetarton Alumni Association Fundraising
description: For the 75th anniversary of our chapter we our raising funds 
theme: minima
baseurl: "gh_pages_test"  # e.g. /repo-name if hosted in a subdirectory
url: "https://cdower.github.io"
markdown: kramdown
plugins:
  - jekyll-feed
